// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class HabitCategories extends Table
    with TableInfo<HabitCategories, HabitCategoriesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  HabitCategories(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
      'id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
      'name', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> color = GeneratedColumn<String>(
      'color', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  @override
  List<GeneratedColumn> get $columns => [id, name, color];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'habit_categories';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  HabitCategoriesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return HabitCategoriesData(
      id: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}id'])!,
      name: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}name'])!,
      color: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}color'])!,
    );
  }

  @override
  HabitCategories createAlias(String alias) {
    return HabitCategories(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class HabitCategoriesData extends DataClass
    implements Insertable<HabitCategoriesData> {
  final String id;
  final String name;
  final String color;
  const HabitCategoriesData(
      {required this.id, required this.name, required this.color});
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['name'] = Variable<String>(name);
    map['color'] = Variable<String>(color);
    return map;
  }

  HabitCategoriesCompanion toCompanion(bool nullToAbsent) {
    return HabitCategoriesCompanion(
      id: Value(id),
      name: Value(name),
      color: Value(color),
    );
  }

  factory HabitCategoriesData.fromJson(Map<String, dynamic> json,
      {ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return HabitCategoriesData(
      id: serializer.fromJson<String>(json['id']),
      name: serializer.fromJson<String>(json['name']),
      color: serializer.fromJson<String>(json['color']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'name': serializer.toJson<String>(name),
      'color': serializer.toJson<String>(color),
    };
  }

  HabitCategoriesData copyWith({String? id, String? name, String? color}) =>
      HabitCategoriesData(
        id: id ?? this.id,
        name: name ?? this.name,
        color: color ?? this.color,
      );
  HabitCategoriesData copyWithCompanion(HabitCategoriesCompanion data) {
    return HabitCategoriesData(
      id: data.id.present ? data.id.value : this.id,
      name: data.name.present ? data.name.value : this.name,
      color: data.color.present ? data.color.value : this.color,
    );
  }

  @override
  String toString() {
    return (StringBuffer('HabitCategoriesData(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('color: $color')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, name, color);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is HabitCategoriesData &&
          other.id == this.id &&
          other.name == this.name &&
          other.color == this.color);
}

class HabitCategoriesCompanion extends UpdateCompanion<HabitCategoriesData> {
  final Value<String> id;
  final Value<String> name;
  final Value<String> color;
  final Value<int> rowid;
  const HabitCategoriesCompanion({
    this.id = const Value.absent(),
    this.name = const Value.absent(),
    this.color = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  HabitCategoriesCompanion.insert({
    required String id,
    required String name,
    required String color,
    this.rowid = const Value.absent(),
  })  : id = Value(id),
        name = Value(name),
        color = Value(color);
  static Insertable<HabitCategoriesData> custom({
    Expression<String>? id,
    Expression<String>? name,
    Expression<String>? color,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (color != null) 'color': color,
      if (rowid != null) 'rowid': rowid,
    });
  }

  HabitCategoriesCompanion copyWith(
      {Value<String>? id,
      Value<String>? name,
      Value<String>? color,
      Value<int>? rowid}) {
    return HabitCategoriesCompanion(
      id: id ?? this.id,
      name: name ?? this.name,
      color: color ?? this.color,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (name.present) {
      map['name'] = Variable<String>(name.value);
    }
    if (color.present) {
      map['color'] = Variable<String>(color.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('HabitCategoriesCompanion(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('color: $color, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class Habits extends Table with TableInfo<Habits, HabitsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Habits(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
      'id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> title = GeneratedColumn<String>(
      'title', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> description = GeneratedColumn<String>(
      'description', aliasedName, true,
      type: DriftSqlType.string,
      requiredDuringInsert: false,
      $customConstraints: 'NULL');
  late final GeneratedColumn<int> lastTimeCompleted = GeneratedColumn<int>(
      'last_time_completed', aliasedName, true,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NULL');
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
      'created_at', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> updatedAt = GeneratedColumn<int>(
      'updated_at', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<String> categoryId = GeneratedColumn<String>(
      'category_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL REFERENCES habit_categories(id)');
  late final GeneratedColumn<int> isPendingSync = GeneratedColumn<int>(
      'is_pending_sync', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (is_pending_sync IN (0, 1))',
      defaultValue: const CustomExpression('0'));
  late final GeneratedColumn<int> steps = GeneratedColumn<int>(
      'steps', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const CustomExpression('0'));
  late final GeneratedColumn<int> isActive = GeneratedColumn<int>(
      'is_active', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1))',
      defaultValue: const CustomExpression('1'));
  late final GeneratedColumn<String> syncStatus = GeneratedColumn<String>(
      'sync_status', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL DEFAULT \'add\'',
      defaultValue: const CustomExpression('\'add\''));
  late final GeneratedColumn<String> icon = GeneratedColumn<String>(
      'icon', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const CustomExpression('\'\''));
  @override
  List<GeneratedColumn> get $columns => [
        id,
        title,
        description,
        lastTimeCompleted,
        createdAt,
        updatedAt,
        categoryId,
        isPendingSync,
        steps,
        isActive,
        syncStatus,
        icon
      ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'habits';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  HabitsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return HabitsData(
      id: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}id'])!,
      title: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}title'])!,
      description: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}description']),
      lastTimeCompleted: attachedDatabase.typeMapping.read(
          DriftSqlType.int, data['${effectivePrefix}last_time_completed']),
      createdAt: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${effectivePrefix}created_at'])!,
      updatedAt: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${effectivePrefix}updated_at'])!,
      categoryId: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}category_id'])!,
      isPendingSync: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${effectivePrefix}is_pending_sync'])!,
      steps: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${effectivePrefix}steps'])!,
      isActive: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${effectivePrefix}is_active'])!,
      syncStatus: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}sync_status'])!,
      icon: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}icon'])!,
    );
  }

  @override
  Habits createAlias(String alias) {
    return Habits(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class HabitsData extends DataClass implements Insertable<HabitsData> {
  final String id;
  final String title;
  final String? description;
  final int? lastTimeCompleted;
  final int createdAt;
  final int updatedAt;
  final String categoryId;
  final int isPendingSync;
  final int steps;
  final int isActive;
  final String syncStatus;
  final String icon;
  const HabitsData(
      {required this.id,
      required this.title,
      this.description,
      this.lastTimeCompleted,
      required this.createdAt,
      required this.updatedAt,
      required this.categoryId,
      required this.isPendingSync,
      required this.steps,
      required this.isActive,
      required this.syncStatus,
      required this.icon});
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['title'] = Variable<String>(title);
    if (!nullToAbsent || description != null) {
      map['description'] = Variable<String>(description);
    }
    if (!nullToAbsent || lastTimeCompleted != null) {
      map['last_time_completed'] = Variable<int>(lastTimeCompleted);
    }
    map['created_at'] = Variable<int>(createdAt);
    map['updated_at'] = Variable<int>(updatedAt);
    map['category_id'] = Variable<String>(categoryId);
    map['is_pending_sync'] = Variable<int>(isPendingSync);
    map['steps'] = Variable<int>(steps);
    map['is_active'] = Variable<int>(isActive);
    map['sync_status'] = Variable<String>(syncStatus);
    map['icon'] = Variable<String>(icon);
    return map;
  }

  HabitsCompanion toCompanion(bool nullToAbsent) {
    return HabitsCompanion(
      id: Value(id),
      title: Value(title),
      description: description == null && nullToAbsent
          ? const Value.absent()
          : Value(description),
      lastTimeCompleted: lastTimeCompleted == null && nullToAbsent
          ? const Value.absent()
          : Value(lastTimeCompleted),
      createdAt: Value(createdAt),
      updatedAt: Value(updatedAt),
      categoryId: Value(categoryId),
      isPendingSync: Value(isPendingSync),
      steps: Value(steps),
      isActive: Value(isActive),
      syncStatus: Value(syncStatus),
      icon: Value(icon),
    );
  }

  factory HabitsData.fromJson(Map<String, dynamic> json,
      {ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return HabitsData(
      id: serializer.fromJson<String>(json['id']),
      title: serializer.fromJson<String>(json['title']),
      description: serializer.fromJson<String?>(json['description']),
      lastTimeCompleted: serializer.fromJson<int?>(json['lastTimeCompleted']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
      updatedAt: serializer.fromJson<int>(json['updatedAt']),
      categoryId: serializer.fromJson<String>(json['categoryId']),
      isPendingSync: serializer.fromJson<int>(json['isPendingSync']),
      steps: serializer.fromJson<int>(json['steps']),
      isActive: serializer.fromJson<int>(json['isActive']),
      syncStatus: serializer.fromJson<String>(json['syncStatus']),
      icon: serializer.fromJson<String>(json['icon']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'title': serializer.toJson<String>(title),
      'description': serializer.toJson<String?>(description),
      'lastTimeCompleted': serializer.toJson<int?>(lastTimeCompleted),
      'createdAt': serializer.toJson<int>(createdAt),
      'updatedAt': serializer.toJson<int>(updatedAt),
      'categoryId': serializer.toJson<String>(categoryId),
      'isPendingSync': serializer.toJson<int>(isPendingSync),
      'steps': serializer.toJson<int>(steps),
      'isActive': serializer.toJson<int>(isActive),
      'syncStatus': serializer.toJson<String>(syncStatus),
      'icon': serializer.toJson<String>(icon),
    };
  }

  HabitsData copyWith(
          {String? id,
          String? title,
          Value<String?> description = const Value.absent(),
          Value<int?> lastTimeCompleted = const Value.absent(),
          int? createdAt,
          int? updatedAt,
          String? categoryId,
          int? isPendingSync,
          int? steps,
          int? isActive,
          String? syncStatus,
          String? icon}) =>
      HabitsData(
        id: id ?? this.id,
        title: title ?? this.title,
        description: description.present ? description.value : this.description,
        lastTimeCompleted: lastTimeCompleted.present
            ? lastTimeCompleted.value
            : this.lastTimeCompleted,
        createdAt: createdAt ?? this.createdAt,
        updatedAt: updatedAt ?? this.updatedAt,
        categoryId: categoryId ?? this.categoryId,
        isPendingSync: isPendingSync ?? this.isPendingSync,
        steps: steps ?? this.steps,
        isActive: isActive ?? this.isActive,
        syncStatus: syncStatus ?? this.syncStatus,
        icon: icon ?? this.icon,
      );
  HabitsData copyWithCompanion(HabitsCompanion data) {
    return HabitsData(
      id: data.id.present ? data.id.value : this.id,
      title: data.title.present ? data.title.value : this.title,
      description:
          data.description.present ? data.description.value : this.description,
      lastTimeCompleted: data.lastTimeCompleted.present
          ? data.lastTimeCompleted.value
          : this.lastTimeCompleted,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
      updatedAt: data.updatedAt.present ? data.updatedAt.value : this.updatedAt,
      categoryId:
          data.categoryId.present ? data.categoryId.value : this.categoryId,
      isPendingSync: data.isPendingSync.present
          ? data.isPendingSync.value
          : this.isPendingSync,
      steps: data.steps.present ? data.steps.value : this.steps,
      isActive: data.isActive.present ? data.isActive.value : this.isActive,
      syncStatus:
          data.syncStatus.present ? data.syncStatus.value : this.syncStatus,
      icon: data.icon.present ? data.icon.value : this.icon,
    );
  }

  @override
  String toString() {
    return (StringBuffer('HabitsData(')
          ..write('id: $id, ')
          ..write('title: $title, ')
          ..write('description: $description, ')
          ..write('lastTimeCompleted: $lastTimeCompleted, ')
          ..write('createdAt: $createdAt, ')
          ..write('updatedAt: $updatedAt, ')
          ..write('categoryId: $categoryId, ')
          ..write('isPendingSync: $isPendingSync, ')
          ..write('steps: $steps, ')
          ..write('isActive: $isActive, ')
          ..write('syncStatus: $syncStatus, ')
          ..write('icon: $icon')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
      id,
      title,
      description,
      lastTimeCompleted,
      createdAt,
      updatedAt,
      categoryId,
      isPendingSync,
      steps,
      isActive,
      syncStatus,
      icon);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is HabitsData &&
          other.id == this.id &&
          other.title == this.title &&
          other.description == this.description &&
          other.lastTimeCompleted == this.lastTimeCompleted &&
          other.createdAt == this.createdAt &&
          other.updatedAt == this.updatedAt &&
          other.categoryId == this.categoryId &&
          other.isPendingSync == this.isPendingSync &&
          other.steps == this.steps &&
          other.isActive == this.isActive &&
          other.syncStatus == this.syncStatus &&
          other.icon == this.icon);
}

class HabitsCompanion extends UpdateCompanion<HabitsData> {
  final Value<String> id;
  final Value<String> title;
  final Value<String?> description;
  final Value<int?> lastTimeCompleted;
  final Value<int> createdAt;
  final Value<int> updatedAt;
  final Value<String> categoryId;
  final Value<int> isPendingSync;
  final Value<int> steps;
  final Value<int> isActive;
  final Value<String> syncStatus;
  final Value<String> icon;
  final Value<int> rowid;
  const HabitsCompanion({
    this.id = const Value.absent(),
    this.title = const Value.absent(),
    this.description = const Value.absent(),
    this.lastTimeCompleted = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.updatedAt = const Value.absent(),
    this.categoryId = const Value.absent(),
    this.isPendingSync = const Value.absent(),
    this.steps = const Value.absent(),
    this.isActive = const Value.absent(),
    this.syncStatus = const Value.absent(),
    this.icon = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  HabitsCompanion.insert({
    required String id,
    required String title,
    this.description = const Value.absent(),
    this.lastTimeCompleted = const Value.absent(),
    required int createdAt,
    required int updatedAt,
    required String categoryId,
    this.isPendingSync = const Value.absent(),
    this.steps = const Value.absent(),
    this.isActive = const Value.absent(),
    this.syncStatus = const Value.absent(),
    this.icon = const Value.absent(),
    this.rowid = const Value.absent(),
  })  : id = Value(id),
        title = Value(title),
        createdAt = Value(createdAt),
        updatedAt = Value(updatedAt),
        categoryId = Value(categoryId);
  static Insertable<HabitsData> custom({
    Expression<String>? id,
    Expression<String>? title,
    Expression<String>? description,
    Expression<int>? lastTimeCompleted,
    Expression<int>? createdAt,
    Expression<int>? updatedAt,
    Expression<String>? categoryId,
    Expression<int>? isPendingSync,
    Expression<int>? steps,
    Expression<int>? isActive,
    Expression<String>? syncStatus,
    Expression<String>? icon,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (title != null) 'title': title,
      if (description != null) 'description': description,
      if (lastTimeCompleted != null) 'last_time_completed': lastTimeCompleted,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
      if (categoryId != null) 'category_id': categoryId,
      if (isPendingSync != null) 'is_pending_sync': isPendingSync,
      if (steps != null) 'steps': steps,
      if (isActive != null) 'is_active': isActive,
      if (syncStatus != null) 'sync_status': syncStatus,
      if (icon != null) 'icon': icon,
      if (rowid != null) 'rowid': rowid,
    });
  }

  HabitsCompanion copyWith(
      {Value<String>? id,
      Value<String>? title,
      Value<String?>? description,
      Value<int?>? lastTimeCompleted,
      Value<int>? createdAt,
      Value<int>? updatedAt,
      Value<String>? categoryId,
      Value<int>? isPendingSync,
      Value<int>? steps,
      Value<int>? isActive,
      Value<String>? syncStatus,
      Value<String>? icon,
      Value<int>? rowid}) {
    return HabitsCompanion(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      lastTimeCompleted: lastTimeCompleted ?? this.lastTimeCompleted,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      categoryId: categoryId ?? this.categoryId,
      isPendingSync: isPendingSync ?? this.isPendingSync,
      steps: steps ?? this.steps,
      isActive: isActive ?? this.isActive,
      syncStatus: syncStatus ?? this.syncStatus,
      icon: icon ?? this.icon,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (title.present) {
      map['title'] = Variable<String>(title.value);
    }
    if (description.present) {
      map['description'] = Variable<String>(description.value);
    }
    if (lastTimeCompleted.present) {
      map['last_time_completed'] = Variable<int>(lastTimeCompleted.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (updatedAt.present) {
      map['updated_at'] = Variable<int>(updatedAt.value);
    }
    if (categoryId.present) {
      map['category_id'] = Variable<String>(categoryId.value);
    }
    if (isPendingSync.present) {
      map['is_pending_sync'] = Variable<int>(isPendingSync.value);
    }
    if (steps.present) {
      map['steps'] = Variable<int>(steps.value);
    }
    if (isActive.present) {
      map['is_active'] = Variable<int>(isActive.value);
    }
    if (syncStatus.present) {
      map['sync_status'] = Variable<String>(syncStatus.value);
    }
    if (icon.present) {
      map['icon'] = Variable<String>(icon.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('HabitsCompanion(')
          ..write('id: $id, ')
          ..write('title: $title, ')
          ..write('description: $description, ')
          ..write('lastTimeCompleted: $lastTimeCompleted, ')
          ..write('createdAt: $createdAt, ')
          ..write('updatedAt: $updatedAt, ')
          ..write('categoryId: $categoryId, ')
          ..write('isPendingSync: $isPendingSync, ')
          ..write('steps: $steps, ')
          ..write('isActive: $isActive, ')
          ..write('syncStatus: $syncStatus, ')
          ..write('icon: $icon, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class HabitCompletions extends Table
    with TableInfo<HabitCompletions, HabitCompletionsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  HabitCompletions(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
      'id', aliasedName, false,
      hasAutoIncrement: true,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT');
  late final GeneratedColumn<String> habitId = GeneratedColumn<String>(
      'habit_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL REFERENCES habits(id)');
  late final GeneratedColumn<int> dateComplete = GeneratedColumn<int>(
      'date_complete', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  @override
  List<GeneratedColumn> get $columns => [id, habitId, dateComplete];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'habit_completions';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  HabitCompletionsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return HabitCompletionsData(
      id: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${effectivePrefix}id'])!,
      habitId: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}habit_id'])!,
      dateComplete: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${effectivePrefix}date_complete'])!,
    );
  }

  @override
  HabitCompletions createAlias(String alias) {
    return HabitCompletions(attachedDatabase, alias);
  }

  @override
  bool get dontWriteConstraints => true;
}

class HabitCompletionsData extends DataClass
    implements Insertable<HabitCompletionsData> {
  final int id;
  final String habitId;
  final int dateComplete;
  const HabitCompletionsData(
      {required this.id, required this.habitId, required this.dateComplete});
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['habit_id'] = Variable<String>(habitId);
    map['date_complete'] = Variable<int>(dateComplete);
    return map;
  }

  HabitCompletionsCompanion toCompanion(bool nullToAbsent) {
    return HabitCompletionsCompanion(
      id: Value(id),
      habitId: Value(habitId),
      dateComplete: Value(dateComplete),
    );
  }

  factory HabitCompletionsData.fromJson(Map<String, dynamic> json,
      {ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return HabitCompletionsData(
      id: serializer.fromJson<int>(json['id']),
      habitId: serializer.fromJson<String>(json['habitId']),
      dateComplete: serializer.fromJson<int>(json['dateComplete']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'habitId': serializer.toJson<String>(habitId),
      'dateComplete': serializer.toJson<int>(dateComplete),
    };
  }

  HabitCompletionsData copyWith(
          {int? id, String? habitId, int? dateComplete}) =>
      HabitCompletionsData(
        id: id ?? this.id,
        habitId: habitId ?? this.habitId,
        dateComplete: dateComplete ?? this.dateComplete,
      );
  HabitCompletionsData copyWithCompanion(HabitCompletionsCompanion data) {
    return HabitCompletionsData(
      id: data.id.present ? data.id.value : this.id,
      habitId: data.habitId.present ? data.habitId.value : this.habitId,
      dateComplete: data.dateComplete.present
          ? data.dateComplete.value
          : this.dateComplete,
    );
  }

  @override
  String toString() {
    return (StringBuffer('HabitCompletionsData(')
          ..write('id: $id, ')
          ..write('habitId: $habitId, ')
          ..write('dateComplete: $dateComplete')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, habitId, dateComplete);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is HabitCompletionsData &&
          other.id == this.id &&
          other.habitId == this.habitId &&
          other.dateComplete == this.dateComplete);
}

class HabitCompletionsCompanion extends UpdateCompanion<HabitCompletionsData> {
  final Value<int> id;
  final Value<String> habitId;
  final Value<int> dateComplete;
  const HabitCompletionsCompanion({
    this.id = const Value.absent(),
    this.habitId = const Value.absent(),
    this.dateComplete = const Value.absent(),
  });
  HabitCompletionsCompanion.insert({
    this.id = const Value.absent(),
    required String habitId,
    required int dateComplete,
  })  : habitId = Value(habitId),
        dateComplete = Value(dateComplete);
  static Insertable<HabitCompletionsData> custom({
    Expression<int>? id,
    Expression<String>? habitId,
    Expression<int>? dateComplete,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (habitId != null) 'habit_id': habitId,
      if (dateComplete != null) 'date_complete': dateComplete,
    });
  }

  HabitCompletionsCompanion copyWith(
      {Value<int>? id, Value<String>? habitId, Value<int>? dateComplete}) {
    return HabitCompletionsCompanion(
      id: id ?? this.id,
      habitId: habitId ?? this.habitId,
      dateComplete: dateComplete ?? this.dateComplete,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (habitId.present) {
      map['habit_id'] = Variable<String>(habitId.value);
    }
    if (dateComplete.present) {
      map['date_complete'] = Variable<int>(dateComplete.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('HabitCompletionsCompanion(')
          ..write('id: $id, ')
          ..write('habitId: $habitId, ')
          ..write('dateComplete: $dateComplete')
          ..write(')'))
        .toString();
  }
}

class HabitStreaks extends Table
    with TableInfo<HabitStreaks, HabitStreaksData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  HabitStreaks(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
      'id', aliasedName, false,
      hasAutoIncrement: true,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT');
  late final GeneratedColumn<String> habitId = GeneratedColumn<String>(
      'habit_id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL REFERENCES habits(id)');
  late final GeneratedColumn<int> currentStreak = GeneratedColumn<int>(
      'current_streak', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  late final GeneratedColumn<int> lastUpdate = GeneratedColumn<int>(
      'last_update', aliasedName, false,
      type: DriftSqlType.int,
      requiredDuringInsert: true,
      $customConstraints: 'NOT NULL');
  @override
  List<GeneratedColumn> get $columns =>
      [id, habitId, currentStreak, lastUpdate];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'habit_streaks';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  HabitStreaksData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return HabitStreaksData(
      id: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${effectivePrefix}id'])!,
      habitId: attachedDatabase.typeMapping
          .read(DriftSqlType.string, data['${effectivePrefix}habit_id'])!,
      currentStreak: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${effectivePrefix}current_streak'])!,
      lastUpdate: attachedDatabase.typeMapping
          .read(DriftSqlType.int, data['${effectivePrefix}last_update'])!,
    );
  }

  @override
  HabitStreaks createAlias(String alias) {
    return HabitStreaks(attachedDatabase, alias);
  }

  @override
  bool get dontWriteConstraints => true;
}

class HabitStreaksData extends DataClass
    implements Insertable<HabitStreaksData> {
  final int id;
  final String habitId;
  final int currentStreak;
  final int lastUpdate;
  const HabitStreaksData(
      {required this.id,
      required this.habitId,
      required this.currentStreak,
      required this.lastUpdate});
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['habit_id'] = Variable<String>(habitId);
    map['current_streak'] = Variable<int>(currentStreak);
    map['last_update'] = Variable<int>(lastUpdate);
    return map;
  }

  HabitStreaksCompanion toCompanion(bool nullToAbsent) {
    return HabitStreaksCompanion(
      id: Value(id),
      habitId: Value(habitId),
      currentStreak: Value(currentStreak),
      lastUpdate: Value(lastUpdate),
    );
  }

  factory HabitStreaksData.fromJson(Map<String, dynamic> json,
      {ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return HabitStreaksData(
      id: serializer.fromJson<int>(json['id']),
      habitId: serializer.fromJson<String>(json['habitId']),
      currentStreak: serializer.fromJson<int>(json['currentStreak']),
      lastUpdate: serializer.fromJson<int>(json['lastUpdate']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'habitId': serializer.toJson<String>(habitId),
      'currentStreak': serializer.toJson<int>(currentStreak),
      'lastUpdate': serializer.toJson<int>(lastUpdate),
    };
  }

  HabitStreaksData copyWith(
          {int? id, String? habitId, int? currentStreak, int? lastUpdate}) =>
      HabitStreaksData(
        id: id ?? this.id,
        habitId: habitId ?? this.habitId,
        currentStreak: currentStreak ?? this.currentStreak,
        lastUpdate: lastUpdate ?? this.lastUpdate,
      );
  HabitStreaksData copyWithCompanion(HabitStreaksCompanion data) {
    return HabitStreaksData(
      id: data.id.present ? data.id.value : this.id,
      habitId: data.habitId.present ? data.habitId.value : this.habitId,
      currentStreak: data.currentStreak.present
          ? data.currentStreak.value
          : this.currentStreak,
      lastUpdate:
          data.lastUpdate.present ? data.lastUpdate.value : this.lastUpdate,
    );
  }

  @override
  String toString() {
    return (StringBuffer('HabitStreaksData(')
          ..write('id: $id, ')
          ..write('habitId: $habitId, ')
          ..write('currentStreak: $currentStreak, ')
          ..write('lastUpdate: $lastUpdate')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(id, habitId, currentStreak, lastUpdate);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is HabitStreaksData &&
          other.id == this.id &&
          other.habitId == this.habitId &&
          other.currentStreak == this.currentStreak &&
          other.lastUpdate == this.lastUpdate);
}

class HabitStreaksCompanion extends UpdateCompanion<HabitStreaksData> {
  final Value<int> id;
  final Value<String> habitId;
  final Value<int> currentStreak;
  final Value<int> lastUpdate;
  const HabitStreaksCompanion({
    this.id = const Value.absent(),
    this.habitId = const Value.absent(),
    this.currentStreak = const Value.absent(),
    this.lastUpdate = const Value.absent(),
  });
  HabitStreaksCompanion.insert({
    this.id = const Value.absent(),
    required String habitId,
    required int currentStreak,
    required int lastUpdate,
  })  : habitId = Value(habitId),
        currentStreak = Value(currentStreak),
        lastUpdate = Value(lastUpdate);
  static Insertable<HabitStreaksData> custom({
    Expression<int>? id,
    Expression<String>? habitId,
    Expression<int>? currentStreak,
    Expression<int>? lastUpdate,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (habitId != null) 'habit_id': habitId,
      if (currentStreak != null) 'current_streak': currentStreak,
      if (lastUpdate != null) 'last_update': lastUpdate,
    });
  }

  HabitStreaksCompanion copyWith(
      {Value<int>? id,
      Value<String>? habitId,
      Value<int>? currentStreak,
      Value<int>? lastUpdate}) {
    return HabitStreaksCompanion(
      id: id ?? this.id,
      habitId: habitId ?? this.habitId,
      currentStreak: currentStreak ?? this.currentStreak,
      lastUpdate: lastUpdate ?? this.lastUpdate,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (habitId.present) {
      map['habit_id'] = Variable<String>(habitId.value);
    }
    if (currentStreak.present) {
      map['current_streak'] = Variable<int>(currentStreak.value);
    }
    if (lastUpdate.present) {
      map['last_update'] = Variable<int>(lastUpdate.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('HabitStreaksCompanion(')
          ..write('id: $id, ')
          ..write('habitId: $habitId, ')
          ..write('currentStreak: $currentStreak, ')
          ..write('lastUpdate: $lastUpdate')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV1 extends GeneratedDatabase {
  DatabaseAtV1(QueryExecutor e) : super(e);
  late final HabitCategories habitCategories = HabitCategories(this);
  late final Habits habits = Habits(this);
  late final HabitCompletions habitCompletions = HabitCompletions(this);
  late final HabitStreaks habitStreaks = HabitStreaks(this);
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities =>
      [habitCategories, habits, habitCompletions, habitStreaks];
  @override
  int get schemaVersion => 1;
}
